---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: "[OpenSSH] Installation"
  package:
    name: "{{ item }}"
    state: installed
  with_flattened:
    - "{{ opensshd_packages }}"
    - "{{ opensshd_packages_extras }}"

- name: "[OpenSSH] Configuration"
  template:
    src: sshd_config.j2
    dest: "{{ opensshd_config_path }}"
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart sshd

- name: "[OpenSSH] Service Initialization"
  service:
    name: "{{sshd_service_name}}"
    state: started
    enabled: yes
