---
- name: restart sshd
  tags:
    - service
    - sshd
  service:
    name: "{{ sshd_service_name }}"
    state: restarted

- name: reload sshd
  tags:
    - service
    - sshd
  service:
    name: "{{ sshd_service_name }}"
    state: reloaded
